image:
  repository: myacr.azurecr.io/myapp
  tag: svt

replicaCount: 3

resources:
  requests:
    cpu: 750m
    memory: 768Mi
  limits:
    cpu: 1500m
    memory: 1536Mi

ingress:
  enabled: true
  host: svt.app.company.com
