image:
  repository: myacr.azurecr.io/myapp
  tag: tst

replicaCount: 2

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

ingress:
  enabled: true
  host: tst.app.company.com
