apiVersion: v1
kind: LimitRange
metadata:
  name: tst-defaults
  namespace: tst
spec:
  limits:
  - type: Container
    default:
      cpu: 750m
      memory: 768Mi
    defaultRequest:
      cpu: 300m
      memory: 384Mi
