apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-secrets-config
  namespace: argocd
spec:
  project: platform-addons
  source:
    repoURL: https://dev.azure.com/your-org/your-project/_git/openshift
    targetRevision: main
    path: gitops/addons/platform-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
