apiVersion: v1
kind: ResourceQuota
metadata:
  name: sit-quota
  namespace: sit
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 12Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    pods: "75"
