apiVersion: v1
kind: ResourceQuota
metadata:
  name: nfr-quota
  namespace: nfr
spec:
  hard:
    requests.cpu: "12"
    requests.memory: 24Gi
    limits.cpu: "24"
    limits.memory: 48Gi
    pods: "120"
