apiVersion: v1
kind: LimitRange
metadata:
  name: preprod-defaults
  namespace: preprod
spec:
  limits:
  - type: Container
    default:
      cpu: 1500m
      memory: 1536Mi
    defaultRequest:
      cpu: 750m
      memory: 768Mi
